require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/**/*.rb'
    - 'vendor/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: braces_for_chaining

Style/CaseEquality:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: true
  EnforcedStyle: braces

Style/NumericLiterals:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: true

Style/SingleLineMethods:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/NestedMethodDefinition:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false
